spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/marketplace}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:0000}

server:
  port: 8080

allowed:
  origins: http://localhost:3000
