spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: 8080

allowed:
  origins: https://marketplace-gg45hy8vp-mariocode13s-projects.vercel.app
