spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: ${PORT:8080}

allowed:
  origins:
    - https://marketplace-gg45hy8vp-mariocode13s-projects.vercel.app
    - https://dealio.org.za
    - https://marketplace-fe-git-master-mariocode13s-projects.vercel.app/

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-change-this-in-production}

# B2 Cloud Storage
b2:
  application:
    key:
      id: ${B2_APPLICATION_KEY_ID:00389696a4df7200000000002}
      name: ${B2_APPLICATION_KEY_NAME:marketplace-listings}
      key: ${B2_APPLICATION_KEY:K003ZxtpV8XrsMqdDL8ZThJwHLICw2Y}
  bucket:
    id: ${B2_BUCKET_ID:9859f6d9467a547d9f570210}
    name: ${B2_BUCKET_NAME:Listings1579}

# Email Configuration
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:mariotyler13@gmail.com}
    password: ${MAIL_PASSWORD:oucx xetl rykd ryts}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Logging
logging:
  level:
    org.springframework.graphql: INFO
    dev.marketplace.marketplace: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.flywaydb: INFO
