spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/marketplace}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:0000}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 900000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: ${DB_URL:jdbc:postgresql://localhost:5432/marketplace}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:0000}
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

allowed:
  origins: http://localhost:3000

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:ZmQ0ZGI5NjQ0NDQxNGFmN2JhNWU5ZjRmYzFhMjA0YjI3ODk5YTc0ZmY3ODJiZmRlMjI5YzBmMTAwMzE2MjBlNg==}

# B2 Cloud Storage
b2:
  application:
    key:
      id: ${B2_APPLICATION_KEY_ID:00389696a4df7200000000002}
      name: ${B2_APPLICATION_KEY_NAME:marketplace-listings}
      key: ${B2_APPLICATION_KEY:K003ZxtpV8XrsMqdDL8ZThJwHLICw2Y}
  bucket:
    id: ${B2_BUCKET_ID:9859f6d9467a547d9f570210}
    name: ${B2_BUCKET_NAME:Listings1579}

# Email Configuration
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:mariotyler13@gmail.com}
    password: ${MAIL_PASSWORD:oucx xetl rykd ryts}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Logging
logging:
  level:
    org.springframework.graphql: DEBUG
    dev.marketplace.marketplace: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: DEBUG
